sudo: required
language: generic
compiler:
- gcc
notifications:
  email:
    on_success: change
    on_failure: always
    recipients:
    - ros-contributions@amazon.com
env:
  matrix:
  - ROS_DISTRO=kinetic ROS_VERSION=1 GAZEBO_VERSION=7
  - ROS_DISTRO=kinetic ROS_VERSION=1 GAZEBO_VERSION=9
  global:
  - SA_NAME=deep-racer
  - SA_PACKAGE_NAME=deepracer_simulation
  - NO_TEST=true
  - GH_USER_NAME="travis-ci"
  - GH_USER_EMAIL="travis@travis-ci.org"
  - AWS_DEFAULT_REGION=us-west-2
  - WORKSPACES="simulation_ws"
  - secure: g13GEF4m4L4qh1w9OyNVvz0ZIBvRdmbEpTSUxQAo9iorOAN/JnLfL/mZtou/0XINZViS0noBSzAj2zqhafL2E/uv1OnHyUD5fmhqyyHyYVdzrDNXwUW+//49hKi2912kjtbp4JyBnY+xhNGqkkxdQFr2Mq6H24O3cnYvFSbPGOaJSC5LzGbYu7tfhL+sl6dTxc0ZzK4pb8MzswQFnDQ5L8RkZFTA4i8UQob4z0E3E6/UB1UOLxqS7uRnqCSOYDkW1hFWAUpp7jMVy4+GCHj377KAez8IwsXN9wJKACkkmcccD/RHbNvlqMuzKOIoK4ub8Y9ZkxTGAmy+nHygUmBibZ32Iqzkgz8c/+Qp40ed7jGod6j83BM40R+s2Q7iM4oEECqWue+NdXSA2uvE0bEQV+iD6hvQ30hvWELG/B055rNFSiLnM4w7+Li60IPhUgavw+I5nuYMk415Io3JGhPTcJAT4AoAKKw34GyBcmcv1okValkf0wIuKmflJ3ib40mu3W2LO1jYeKJAppyyquZNLC9TZi6J3a8eI2VwU8IfMAJwEI3eNoBzEyFX841UYNYGUNYiGfj3wNTnIzvkH8R4jDd5S8fYZmbeJD07FIQE53z9acFYUtpBxW4AHjIbtzEVyu6UrF9WdeLkQrZmiKH2/CNB3/tqx9tr4ULj5qModVc=
  - secure: lKLTNPJGZhY/2cCQYI2M9s10MaOj81rH0CuZm7EdpHvM8SSCA2+LUVfpi58gGNU0/qC5cyGjP7i17CCIIEUF0HHiX+Kt57vbWcvDAOHlKVSEWie+xHtlLXc5Fd8zY7dlTXXY41iiMPftAODO8EYnoBqUBmGNJHKxKrovDfgkmnTN3a+EXDoegXV2glo9RmwvCcX30JMPKZkFZ2FRBPcUSk61GZIdF50fHxiNWHUoXlM6+4WN+iOGoO5BTAd4kKTHju8/gAw1fn1dWUODButm5pLyj7D0nmRdgZh9C6ruAMxfr4yJpzPSDPMMlDf1fVfYSt3o7J3uGbAm3rj7J5B7RmcDmkfMnJmG6cYcfz/N9bIGcrz0YBOLIysI+PsR4HsFAY9WUSKgIAaz8KpniIhk6Z05ZEZV5Sx/JgUH0e9uBI3OHGQvQH/FNVfLAL9Zt+0NIAfDJptJayB+0VXmkX7xlM6dHN0//tqc5wJ+c4ovJfegA3ri9dtiiPtW3swqfTIlqrctjCXIQM2LSvC2v+IH536OyDxlvX5jVoQPvHqclx7hPkHdwHFRczbMgj8JMDhoY7EhGmnfCHWHwVZqqN8s9llJSTV9IwXZahbWXt3UzdXKHZLbNvnoBFoDcKPMRUfwUBCJWE1q/ewvUKTmNI9f+//s0fKlx+74kRHlJ1Vtal0=
before_install:
- openssl aes-256-cbc -K $encrypted_670ffd5d6b74_key -iv $encrypted_670ffd5d6b74_iv
  -in github_deploy.pem.enc -out github_deploy.pem -d
- pip install --user awscli
install:
- git clone https://github.com/aws-robotics/travis-scripts.git .ros_ci
script:
- ". .ros_ci/add_tag.sh"
- travis_wait 50 .ros_ci/ce_build.sh
before_deploy:
- ". .ros_ci/before_deploy.sh"
deploy:
- provider: s3
  access_key_id: "$AWS_ACCESS_KEY_ID"
  secret_access_key: "$AWS_SECRET_ACCESS_KEY"
  bucket: "$S3_BUCKET_NAME"
  local_dir: shared
  skip_cleanup: true
  wait-until-deployed: true
  on:
    branch: master
  upload-dir: travis/${SA_NAME}/${ROS_DISTRO}/gazebo${GAZEBO_VERSION}
- provider: script
  script: bash .ros_ci/codepipeline_deploy.sh
  on:
    branch: master
after_deploy:
- ".ros_ci/post_deploy.sh"
